### ISSUE TITLE
Change xAxis color from black to white

### ISSUE THREAD

**Issue by HardRock4Life** [Microsoft/PowerBI-visuals-TimeBrush#42]
What is the .css file that is responsible for changing text color in xAxis? I need to change text color from black to white

**Comment by stopyoukid** [comment]
https://github.com/microsoft/PowerBI-visuals-TimeBrush/blob/a1cb94b6f9bd2ec4931b17b8a3e5301e98410e35/packages/timebrush/css/Base.scss#L30-L35

**Comment by HardRock4Life** [comment]
.axis path
{
fill: #fff;
stroke: #fff;
}

.axis text
{
fill: #fff;
}

.axis line
{
fill: #fff;
stroke: #fff;
shape-rendering: crispEdges;
}

Made it so, but it doesn't work. Also, what does "crispEdges" do?

**Comment by stopyoukid** [comment]
So, you're likely not seeing the updates in PowerBI.  PowerBI has a unique guid associated with visuals, which can prevent seeing updates if the visual has already been published to app source at all.  Change this guid value here to something else using alphanumeric characters, and try again:

https://github.com/microsoft/PowerBI-visuals-TimeBrush/blob/844cda522e9c70deb22d571b6e595ce73fc178ef/packages/timebrush-powerbi/pbiviz.json#L5

`shapeRendering` - https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering#Usage_notes

**Comment by HardRock4Life** [comment]
Ok, I will try and show the result.

ср, 7 Авг 2019, 18:32 David Tittsworth <notifications@github.com>:

**Comment by HardRock4Life** [comment]
Yes, it worked out. One last question: how can I change the text language?

**Comment by stopyoukid** [comment]
I assume you mean for the dates?  I haven't done too much localization with d3, so it will require research on your part.  However, a quick internet search pulled this up: https://stackoverflow.com/a/25626318

**Comment by HardRock4Life** [comment]
Thank you greatly for your time, David!
